package com.paulmount.paulfoliodisplay.model;

import java.util.Collection;

public record GithubRepo(String id, String nodeId, String name, String fullName, String isPrivate, Object owner,
                         String htmlUrl, String description, String isFork, String url, String forksUrl, String keysUrl,
                         String collaborators, String teamsUrl, String hooksUrl, String issueEvents, String assigneesUrl,
                         String branchesUrl, String tagsUrl, String blobsUrl, String gitTagsUrl, String gitRefsUrl,
                         String treesUrl, String statusesUrl, String languagesUrl,
                         String stargazersUrl,
                         String contributorsUrl,
                         String subscribersUrl,
                         String subscriptionUrl,
                         String commitsUrl,
                         String gitCommitsUrl,
                         String commentsUrl,
                         String issueCommentUrl,
                         String contentsUrl,
                         String compareUrl,
                         String mergesUrl,
                         String archiveUrl,
                         String downloadsUrl,
                         String issuesUrl,
                         String pullsUrl,
                         String milestonesUrl,
                         String notificationsUrl,
                         String labelsUrl,
                         String releasesUrl,
                         String deploymentsUrl,
                         String createdAt,
                         String updatedAt,
                         String pushedAt,
                         String gitUrl,
                         String sshUrl,
                         String cloneUrl,
                         String svnUrl,
                         String homepage,
                         Integer size,
                         Integer stargazersCount,
                         Integer watchersCount,
                         String language,
                         String hasIssues,
                         String hasProjects,
                         String hasDownloads,
                         String hasWiki,
                         String hasPages,
                         String hasDiscussions,
                         Integer forksCount,
                         String mirror_url,
                         String archived,
                         String disabled,
                         Integer openIssuesCount,
                         Object license,
                         String allowForking,
                         String isTemplate,
                         String webCommitSignoffRequired,
                         Collection<String> topics,
                         String visibility,
                         Integer forks,
                         Integer openIssues,
                         Integer watchers,
                         String defaultBranch) {
}

/* {id=291817054,
node_id=MDEwOlJlcG9zaXRvcnkyOTE4MTcwNTQ=,
name=haikus-online,
full_name=accuPaul/haikus-online,
private=false,
owner={login=accuPaul, id=60938284, node_id=MDQ6VXNlcjYwOTM4Mjg0, avatar_url=https://avatars.githubusercontent.com/u/60938284?v=4, gravatar_id=, url=https://api.github.com/users/accuPaul, html_url=https://github.com/accuPaul, followers_url=https://api.github.com/users/accuPaul/followers, following_url=https://api.github.com/users/accuPaul/following{/other_user}, gists_url=https://api.github.com/users/accuPaul/gists{/gist_id}, starred_url=https://api.github.com/users/accuPaul/starred{/owner}{/repo}, subscriptions_url=https://api.github.com/users/accuPaul/subscriptions, organizations_url=https://api.github.com/users/accuPaul/orgs, repos_url=https://api.github.com/users/accuPaul/repos, events_url=https://api.github.com/users/accuPaul/events{/privacy}, received_events_url=https://api.github.com/users/accuPaul/received_events, type=User, site_admin=false},
html_url=https://github.com/accuPaul/haikus-online,
description=null,
fork=false,
url=https://api.github.com/repos/accuPaul/haikus-online,
forks_url=https://api.github.com/repos/accuPaul/haikus-online/forks,
keys_url=https://api.github.com/repos/accuPaul/haikus-online/keys{/key_id},
collaborators_url=https://api.github.com/repos/accuPaul/haikus-online/collaborators{/collaborator},
teams_url=https://api.github.com/repos/accuPaul/haikus-online/teams,
hooks_url=https://api.github.com/repos/accuPaul/haikus-online/hooks,
issue_events_url=https://api.github.com/repos/accuPaul/haikus-online/issues/events{/number},
events_url=https://api.github.com/repos/accuPaul/haikus-online/events,
assignees_url=https://api.github.com/repos/accuPaul/haikus-online/assignees{/user},
branches_url=https://api.github.com/repos/accuPaul/haikus-online/branches{/branch},
tags_url=https://api.github.com/repos/accuPaul/haikus-online/tags,
blobs_url=https://api.github.com/repos/accuPaul/haikus-online/git/blobs{/sha},
git_tags_url=https://api.github.com/repos/accuPaul/haikus-online/git/tags{/sha},
git_refs_url=https://api.github.com/repos/accuPaul/haikus-online/git/refs{/sha},
trees_url=https://api.github.com/repos/accuPaul/haikus-online/git/trees{/sha},
statuses_url=https://api.github.com/repos/accuPaul/haikus-online/statuses/{sha},
languages_url=https://api.github.com/repos/accuPaul/haikus-online/languages,
stargazers_url=https://api.github.com/repos/accuPaul/haikus-online/stargazers,
contributors_url=https://api.github.com/repos/accuPaul/haikus-online/contributors,
subscribers_url=https://api.github.com/repos/accuPaul/haikus-online/subscribers,
subscription_url=https://api.github.com/repos/accuPaul/haikus-online/subscription,
commits_url=https://api.github.com/repos/accuPaul/haikus-online/commits{/sha},
git_commits_url=https://api.github.com/repos/accuPaul/haikus-online/git/commits{/sha},
comments_url=https://api.github.com/repos/accuPaul/haikus-online/comments{/number},
issue_comment_url=https://api.github.com/repos/accuPaul/haikus-online/issues/comments{/number},
contents_url=https://api.github.com/repos/accuPaul/haikus-online/contents/{+path},
compare_url=https://api.github.com/repos/accuPaul/haikus-online/compare/{base}...{head},
merges_url=https://api.github.com/repos/accuPaul/haikus-online/merges,
archive_url=https://api.github.com/repos/accuPaul/haikus-online/{archive_format}{/ref},
downloads_url=https://api.github.com/repos/accuPaul/haikus-online/downloads,
issues_url=https://api.github.com/repos/accuPaul/haikus-online/issues{/number},
pulls_url=https://api.github.com/repos/accuPaul/haikus-online/pulls{/number},
milestones_url=https://api.github.com/repos/accuPaul/haikus-online/milestones{/number},
notifications_url=https://api.github.com/repos/accuPaul/haikus-online/notifications{?since,all,participating},
labels_url=https://api.github.com/repos/accuPaul/haikus-online/labels{/name},
releases_url=https://api.github.com/repos/accuPaul/haikus-online/releases{/id},
deployments_url=https://api.github.com/repos/accuPaul/haikus-online/deployments,
created_at=2020-08-31T20:24:24Z, updated_at=2020-09-03T20:22:17Z,
pushed_at=2021-01-27T17:09:39Z,
git_url=git://github.com/accuPaul/haikus-online.git,
ssh_url=git@github.com:accuPaul/haikus-online.git,
clone_url=https://github.com/accuPaul/haikus-online.git,
svn_url=https://github.com/accuPaul/haikus-online,
homepage=null,
size=217,
stargazers_count=0,
watchers_count=0,
language=JavaScript,
has_issues=true,
has_projects=true,
has_downloads=true,
has_wiki=true,
has_pages=false,
has_discussions=false,
forks_count=0,
mirror_url=null,
archived=false,
disabled=false,
open_issues_count=0,
license={key=gpl-3.0, name=GNU General Public License v3.0, spdx_id=GPL-3.0, url=https://api.github.com/licenses/gpl-3.0, node_id=MDc6TGljZW5zZTk=},
allow_forking=true,
is_template=false,
web_commit_signoff_required=false,
topics=[],
visibility=public,
forks=0,
open_issues=0,
watchers=0,
default_branch=master}
 */